root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  billing/product-plans: ./billing/change-product-plan.md
  versioning: ./other/versioning.md
  rule-flow/debug-mode-in-rule-flow: ./tutorials/create-simple-rule-flow.md
  decision-tables/rule-state: ./other/rule-state.md
  decision-tables/versioning: ./other/versioning.md
  rule-flow/versioning: ./other/versioning.md
  on-premise-docker/server-container-and: ./on-premise-docker/environment-variables.md
  decision-tables/search-and-filter: ./other/tagging.md
  rule-state: ./other/rule-state.md
