--------------------------------------------------------
--  DDL for Table PARALLEL_LOGS
--------------------------------------------------------

  CREATE TABLE "SYS"."PARALLEL_LOGS" 
   (	"CHUNK_ID" NUMBER, 
	"TASK_OWNER" VARCHAR2(128 BYTE), 
	"TASK_NAME" VARCHAR2(128 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"START_ROWID" ROWID, 
	"END_ROWID" ROWID, 
	"START_ID" NUMBER, 
	"END_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(128 BYTE), 
	"START_TS" TIMESTAMP (6), 
	"END_TS" TIMESTAMP (6), 
	"ERROR_CODE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARALLEL_LOGS
--------------------------------------------------------

  ALTER TABLE "SYS"."PARALLEL_LOGS" MODIFY ("CHUNK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARALLEL_LOGS" MODIFY ("TASK_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SYS"."PARALLEL_LOGS" MODIFY ("TASK_NAME" NOT NULL ENABLE);
